begin;
select plan(16);
select has_table('public','users','users exists');
select has_table('public','sessions','sessions exists');
select has_table('public','accounts','accounts exists');
select has_table('public','verification_tokens','verification tokens exist');
select has_table('public','email_verification_codes','email verification codes exist');
select has_column('public','users','recovery_email_verified_at','verified login email timestamp exists');
select has_table('public','admin_audit_events','audit table exists');
select has_column('public','applications','owner_id','applications have owner');
select has_column('public','import_batches','owner_id','batches have owner');
select function_returns('public','assert_application_owner',array['text','uuid'],'void','owner assertion exists');
select col_not_null('public','applications','owner_id','application owner is required');
select col_not_null('public','import_batches','owner_id','batch owner is required');
select col_default_is('public','users','role','''user''::text','new users default to user');
insert into users(id,display_name,email,role) values ('admin-a','Admin A','admin-a@example.test','admin'),('user-a','User A','user-a@example.test','user');
select lives_ok($$select update_user_access_as('admin-a','user-a','admin',false)$$,'admin can promote user');
select is((select count(*) from admin_audit_events where event_type='promote_admin'),1::bigint,'role change is audited');
select throws_ok($$select update_user_access_as('user-a','user-a','user',false)$$,'23514','last_admin_guard','last admin is protected');
select * from finish();
rollback;
