begin;
select plan(15);
select has_table('public','interview_reviews','interview reviews exist');
select has_table('public','interview_questions','interview questions exist');
select has_table('public','interview_action_items','interview action items exist');
select col_is_pk('public','interview_reviews','id','review id is primary key');
select col_not_null('public','interview_reviews','owner_id','review owner required');
select fk_ok('public','interview_reviews','application_id','public','applications','id','application cascade foreign key');
select fk_ok('public','interview_reviews','stage_occurrence_id','public','application_stage_occurrences','id','stage nullable foreign key');
select fk_ok('public','interview_questions','interview_review_id','public','interview_reviews','id','question cascade foreign key');
select fk_ok('public','interview_action_items','interview_review_id','public','interview_reviews','id','action cascade foreign key');
select has_index('public','interview_reviews','interview_reviews_owner_date_idx','owner date index exists');
select has_index('public','interview_questions','interview_questions_search_idx','question search index exists');
select ok((select relrowsecurity from pg_class where oid='public.interview_reviews'::regclass),'review RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.interview_questions'::regclass),'question RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.interview_action_items'::regclass),'action RLS enabled');
select throws_ok($$insert into public.interview_reviews(owner_id,application_id,stage_snapshot,interviewed_on) values('missing',gen_random_uuid(),'written_test',current_date)$$,'23503');
select * from finish();
rollback;
