begin;
select plan(16);
select has_table('public','job_market_companies','job market companies exist');
select has_table('public','job_market_sources','job market sources exist');
select has_table('public','job_market_campaigns','job market campaigns exist');
select has_table('public','job_market_posts','public jobs exist');
select has_table('public','job_market_source_records','provenance exists');
select has_table('public','job_market_sync_runs','sync audit exists');
select has_table('public','job_market_events','explanation events exist');
select has_table('public','job_market_campaign_favorites','favorites exist');
select has_table('public','application_job_market_links','private application links exist');
select col_is_pk('public','job_market_campaign_favorites',array['owner_id','campaign_id'],'favorites are owner scoped');
select col_is_pk('public','job_market_source_records',array['source_id','external_job_id'],'source identity is stable');
select has_index('public','job_market_sources','job_market_source_claim_idx','source claim index exists');
select has_index('public','job_market_campaigns','job_market_campaign_browse_idx','campaign browse index exists');
select has_index('public','application_job_market_links','application_job_market_owner_idx','private link owner index exists');
select ok((select relrowsecurity from pg_class where oid='public.job_market_campaign_favorites'::regclass),'favorites enable RLS');
select ok((select relrowsecurity from pg_class where oid='public.application_job_market_links'::regclass),'application links enable RLS');
select * from finish();
rollback;
