import type { SourceAdapterKind } from "../domain/entities";

export type DefaultSourceCatalogEntry = {
  identityKey: string;
  companyName: string;
  companyType: string;
  industry: string;
  websiteUrl: string;
  adapter: SourceAdapterKind;
  externalKey: string;
  baseUrl: string;
  allowedHosts: string[];
  countryCodes: string[];
  syncIntervalMinutes: number;
};

function mokaSource(input: {
  identityKey: string;
  companyName: string;
  companyType: string;
  industry: string;
  orgId: string;
  mode: "social" | "campus";
  siteId?: string;
  portal?:
    "social-recruitment" | "campus-recruitment" | "apply" | "campus_apply";
}) {
  const portal =
    input.portal ??
    (input.mode === "campus" ? "campus-recruitment" : "social-recruitment");
  const sitePath = input.siteId ? `/${input.siteId}` : "";
  return {
    identityKey: input.identityKey,
    companyName: input.companyName,
    companyType: input.companyType,
    industry: input.industry,
    websiteUrl: `https://app.mokahr.com/${portal}/${input.orgId}${sitePath}`,
    adapter: "moka" as const,
    externalKey: `${input.orgId}|${input.mode}|${input.siteId ?? ""}`,
    baseUrl: "https://api.mokahr.com/",
    allowedHosts: ["api.mokahr.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  };
}

function publicAtsSource(input: {
  identityKey: string;
  companyName: string;
  industry: string;
  adapter: "smartrecruiters" | "greenhouse" | "lever";
  externalKey: string;
}) {
  const configuration = {
    smartrecruiters: {
      websiteHost: "jobs.smartrecruiters.com",
      baseUrl: "https://api.smartrecruiters.com/",
      allowedHost: "api.smartrecruiters.com",
    },
    greenhouse: {
      websiteHost: "job-boards.greenhouse.io",
      baseUrl: "https://boards-api.greenhouse.io/",
      allowedHost: "boards-api.greenhouse.io",
    },
    lever: {
      websiteHost: "jobs.lever.co",
      baseUrl: "https://api.lever.co/",
      allowedHost: "api.lever.co",
    },
  }[input.adapter];
  return {
    identityKey: input.identityKey,
    companyName: input.companyName,
    companyType: "外企",
    industry: input.industry,
    websiteUrl: `https://${configuration.websiteHost}/${input.externalKey}`,
    adapter: input.adapter,
    externalKey: input.externalKey,
    baseUrl: configuration.baseUrl,
    allowedHosts: [configuration.allowedHost],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  } satisfies DefaultSourceCatalogEntry;
}

function feishuSource(input: {
  identityKey: string;
  companyName: string;
  industry: string;
  host: string;
  path?: string;
}) {
  return {
    identityKey: input.identityKey,
    companyName: input.companyName,
    companyType: "民营企业",
    industry: input.industry,
    websiteUrl: `https://${input.host}/${input.path ?? ""}`,
    adapter: "feishu" as const,
    externalKey: `${input.host}|${input.path ?? ""}`,
    baseUrl: `https://${input.host}/`,
    allowedHosts: [input.host],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  } satisfies DefaultSourceCatalogEntry;
}

const EXPANDED_MOKA_SOURCES = [
  {
    identityKey: "default:bonditech-cn",
    companyName: "邦德激光",
    companyType: "民营企业",
    industry: "激光装备 / 智能制造",
    orgId: "bonditech",
    mode: "social",
    siteId: "143552",
  },
  {
    identityKey: "default:yoka-cn",
    companyName: "友谊时光",
    companyType: "上市公司",
    industry: "游戏 / 数字娱乐",
    orgId: "yokagames",
    mode: "social",
    siteId: "41939",
  },
  {
    identityKey: "default:yongshi-cn",
    companyName: "勇仕网络",
    companyType: "民营企业",
    industry: "游戏 / 软件",
    orgId: "ys4fun",
    mode: "campus",
    siteId: "45636",
  },
  {
    identityKey: "default:ruijie-cn",
    companyName: "锐捷网络",
    companyType: "上市公司",
    industry: "网络设备 / 云计算",
    orgId: "ruijie",
    mode: "campus",
    siteId: "136206",
  },
  {
    identityKey: "default:perfect-world-cn",
    companyName: "完美世界",
    companyType: "上市公司",
    industry: "游戏 / 影视",
    orgId: "pwrd",
    mode: "campus",
    siteId: "144582",
  },
  {
    identityKey: "default:cti-cn",
    companyName: "华测检测",
    companyType: "上市公司",
    industry: "检测认证 / 技术服务",
    orgId: "cti",
    mode: "social",
    siteId: "145979",
  },
  {
    identityKey: "default:xcmg-cn",
    companyName: "徐工集团",
    companyType: "国有企业",
    industry: "工程机械 / 智能制造",
    orgId: "xcmg",
    mode: "campus",
    siteId: "148091",
  },
  {
    identityKey: "default:leisai-cn",
    companyName: "雷赛智能",
    companyType: "上市公司",
    industry: "工业自动化 / 机器人",
    orgId: "leisai",
    mode: "campus",
    siteId: "115939",
  },
  {
    identityKey: "default:zhihu-cn",
    companyName: "知乎",
    companyType: "上市公司",
    industry: "互联网 / 内容社区",
    orgId: "zhihu",
    mode: "social",
    siteId: "78336",
    portal: "apply",
  },
  {
    identityKey: "default:sohu-cn",
    companyName: "搜狐",
    companyType: "上市公司",
    industry: "互联网 / 媒体",
    orgId: "sohu",
    mode: "campus",
    siteId: "28313",
    portal: "campus_apply",
  },
  {
    identityKey: "default:changyou-cn",
    companyName: "畅游",
    companyType: "上市公司",
    industry: "游戏 / 数字娱乐",
    orgId: "cyou-inc",
    mode: "social",
    siteId: "42232",
  },
  {
    identityKey: "default:luster-cn",
    companyName: "凌云光",
    companyType: "上市公司",
    industry: "机器视觉 / 智能制造",
    orgId: "lusterinc",
    mode: "social",
    siteId: "44881",
  },
  {
    identityKey: "default:micateam-cn",
    companyName: "散爆网络",
    companyType: "民营企业",
    industry: "游戏 / 数字娱乐",
    orgId: "micateam",
    mode: "social",
    siteId: "142158",
  },
  {
    identityKey: "default:shangyou-cn",
    companyName: "尚游游戏",
    companyType: "民营企业",
    industry: "游戏 / 软件",
    orgId: "shangyou",
    mode: "social",
    siteId: "42165",
  },
  {
    identityKey: "default:microfun-cn",
    companyName: "柠檬微趣",
    companyType: "民营企业",
    industry: "游戏 / 移动互联网",
    orgId: "microfunhr",
    mode: "social",
    siteId: "36715",
    portal: "apply",
  },
  {
    identityKey: "default:duxiaoman-cn",
    companyName: "度小满",
    companyType: "民营企业",
    industry: "金融科技 / 人工智能",
    orgId: "duxiaoman",
    mode: "campus",
    siteId: "74050",
    portal: "campus_apply",
  },
  {
    identityKey: "default:xishanju-cn",
    companyName: "西山居",
    companyType: "民营企业",
    industry: "游戏 / 数字娱乐",
    orgId: "xishanju",
    mode: "campus",
    siteId: "37430",
  },
  {
    identityKey: "default:megvii-cn",
    companyName: "旷视科技",
    companyType: "民营企业",
    industry: "人工智能 / 计算机视觉",
    orgId: "megviihr",
    mode: "social",
    siteId: "38641",
  },
  {
    identityKey: "default:douyu-cn",
    companyName: "斗鱼",
    companyType: "上市公司",
    industry: "直播 / 游戏 / 互联网",
    orgId: "douyu",
    mode: "campus",
    siteId: "21995",
  },
  {
    identityKey: "default:envision-cn",
    companyName: "远景科技集团",
    companyType: "民营企业",
    industry: "新能源 / 智能物联",
    orgId: "envisiongroup",
    mode: "campus",
    siteId: "43123",
  },
  {
    identityKey: "default:geely-cn",
    companyName: "吉利控股集团",
    companyType: "民营企业",
    industry: "汽车 / 新能源 / 智能出行",
    orgId: "geely",
    mode: "campus",
    siteId: "78436",
  },
  {
    identityKey: "default:wanda-commercial-cn",
    companyName: "万达商管",
    companyType: "民营企业",
    industry: "商业运营 / 地产",
    orgId: "wandacm",
    mode: "campus",
    siteId: "164049",
  },
  {
    identityKey: "default:tuyoo-cn",
    companyName: "途游游戏",
    companyType: "民营企业",
    industry: "游戏 / 互联网",
    orgId: "tuyoogame",
    mode: "social",
    siteId: "73946",
  },
  {
    identityKey: "default:leyuansu-cn",
    companyName: "乐元素",
    companyType: "民营企业",
    industry: "游戏 / 数字娱乐",
    orgId: "leyuansu",
    mode: "social",
    siteId: "2358",
    portal: "apply",
  },
  {
    identityKey: "default:kuro-cn",
    companyName: "库洛游戏",
    companyType: "民营企业",
    industry: "游戏 / 数字娱乐",
    orgId: "kuro",
    mode: "social",
    siteId: "46886",
  },
  {
    identityKey: "default:kingnet-cn",
    companyName: "恺英网络",
    companyType: "上市公司",
    industry: "游戏 / 互联网",
    orgId: "kingnet",
    mode: "social",
    siteId: "2247",
    portal: "apply",
  },
  {
    identityKey: "default:rastar-cn",
    companyName: "星辉娱乐",
    companyType: "上市公司",
    industry: "游戏 / 文体娱乐",
    orgId: "rastar",
    mode: "social",
    siteId: "96228",
  },
  {
    identityKey: "default:yostar-cn",
    companyName: "悠星网络",
    companyType: "民营企业",
    industry: "游戏 / 数字娱乐",
    orgId: "yostar",
    mode: "social",
    siteId: "26843",
    portal: "apply",
  },
  {
    identityKey: "default:tianyan-capital-cn",
    companyName: "天演资本",
    companyType: "民营企业",
    industry: "量化投资 / 金融科技",
    orgId: "tianyancapital",
    mode: "social",
    siteId: "98901",
  },
  {
    identityKey: "default:xinyongfei-cn",
    companyName: "芯永飞",
    companyType: "民营企业",
    industry: "半导体 / 集成电路",
    orgId: "xinyongfei",
    mode: "social",
    siteId: "98087",
  },
  {
    identityKey: "default:tuhu-cn",
    companyName: "途虎养车",
    companyType: "上市公司",
    industry: "汽车服务 / 电商",
    orgId: "tuhu",
    mode: "campus",
    siteId: "28398",
    portal: "campus_apply",
  },
  {
    identityKey: "default:sangfor-cn",
    companyName: "深信服",
    companyType: "上市公司",
    industry: "网络安全 / 云计算",
    orgId: "sangfor",
    mode: "campus",
    siteId: "27944",
    portal: "campus_apply",
  },
  {
    identityKey: "default:hypergryph-cn",
    companyName: "鹰角网络",
    companyType: "民营企业",
    industry: "游戏 / 数字娱乐",
    orgId: "hypergryph",
    mode: "campus",
    siteId: "26326",
    portal: "campus_apply",
  },
  {
    identityKey: "default:budweiser-cn",
    companyName: "百威中国",
    companyType: "外企",
    industry: "食品饮料 / 消费品",
    orgId: "budweiser",
    mode: "campus",
    siteId: "148097",
  },
  {
    identityKey: "default:tesla-cn",
    companyName: "特斯拉中国",
    companyType: "外企",
    industry: "新能源汽车 / 能源",
    orgId: "tesla",
    mode: "social",
    siteId: "46129",
  },
  {
    identityKey: "default:bayer-cn",
    companyName: "拜耳中国",
    companyType: "外企",
    industry: "医药 / 农业科技",
    orgId: "bayer",
    mode: "social",
    siteId: "148387",
  },
  {
    identityKey: "default:kpmg-cn",
    companyName: "毕马威中国",
    companyType: "外企",
    industry: "审计 / 咨询 / 专业服务",
    orgId: "kpmg",
    mode: "campus",
    siteId: "74356",
  },
  {
    identityKey: "default:bsh-cn",
    companyName: "博西家电中国",
    companyType: "外企",
    industry: "家用电器 / 智能制造",
    orgId: "bshg",
    mode: "social",
    siteId: "28741",
    portal: "apply",
  },
  {
    identityKey: "default:line-man-cn",
    companyName: "LINE MAN Wongnai",
    companyType: "外企",
    industry: "互联网 / 本地生活",
    orgId: "linecorp",
    mode: "social",
    siteId: "150828",
  },
  {
    identityKey: "default:phoenix-contact-cn",
    companyName: "菲尼克斯电气中国",
    companyType: "外企",
    industry: "工业自动化 / 电气",
    orgId: "phoenixcontact",
    mode: "social",
    siteId: "99349",
    portal: "apply",
  },
] as const;

const EXPANDED_PUBLIC_ATS_SOURCES = [
  {
    identityKey: "default:sobi-cn",
    companyName: "Sobi中国",
    industry: "生物医药",
    adapter: "smartrecruiters",
    externalKey: "Sobi",
  },
  {
    identityKey: "default:aumovio-cn",
    companyName: "AUMOVIO中国",
    industry: "汽车科技 / 智能出行",
    adapter: "smartrecruiters",
    externalKey: "Aumovio",
  },
  {
    identityKey: "default:colliers-cn",
    companyName: "高力国际中国",
    industry: "房地产服务 / 咨询",
    adapter: "smartrecruiters",
    externalKey: "Colliers1",
  },
  {
    identityKey: "default:canva-cn",
    companyName: "Canva中国",
    industry: "设计软件 / 互联网",
    adapter: "smartrecruiters",
    externalKey: "Canva",
  },
  {
    identityKey: "default:konecranes-cn",
    companyName: "科尼中国",
    industry: "工业设备 / 智能制造",
    adapter: "smartrecruiters",
    externalKey: "Konecranes",
  },
  {
    identityKey: "default:solidigm-cn",
    companyName: "Solidigm中国",
    industry: "半导体 / 数据存储",
    adapter: "smartrecruiters",
    externalKey: "Solidigm",
  },
  {
    identityKey: "default:beumer-cn",
    companyName: "伯曼机械中国",
    industry: "物流装备 / 智能制造",
    adapter: "smartrecruiters",
    externalKey: "BEUMERGroup1",
  },
  {
    identityKey: "default:psi-cro-cn",
    companyName: "PSI CRO中国",
    industry: "临床研究 / 医药",
    adapter: "smartrecruiters",
    externalKey: "PSICRO",
  },
  {
    identityKey: "default:roland-berger-cn",
    companyName: "罗兰贝格中国",
    industry: "管理咨询",
    adapter: "smartrecruiters",
    externalKey: "rolandberger",
  },
  {
    identityKey: "default:zenni-cn",
    companyName: "Zenni Optical中国",
    industry: "眼镜 / 电商 / 制造",
    adapter: "greenhouse",
    externalKey: "zennioptical",
  },
  {
    identityKey: "default:altium-cn",
    companyName: "Altium中国",
    industry: "EDA / 企业软件",
    adapter: "greenhouse",
    externalKey: "altium",
  },
  {
    identityKey: "default:guidepoint-cn",
    companyName: "Guidepoint中国",
    industry: "专家咨询 / 行业研究",
    adapter: "greenhouse",
    externalKey: "guidepoint",
  },
  {
    identityKey: "default:appier-cn",
    companyName: "Appier中国",
    industry: "人工智能 / 营销科技",
    adapter: "greenhouse",
    externalKey: "appier",
  },
  {
    identityKey: "default:moloco-cn",
    companyName: "Moloco中国",
    industry: "人工智能 / 广告科技",
    adapter: "greenhouse",
    externalKey: "moloco",
  },
  {
    identityKey: "default:ideo-cn",
    companyName: "IDEO中国",
    industry: "设计咨询 / 创新",
    adapter: "greenhouse",
    externalKey: "ideo",
  },
  {
    identityKey: "default:brooks-running-cn",
    companyName: "Brooks Running中国",
    industry: "运动用品 / 零售",
    adapter: "lever",
    externalKey: "brooksrunning",
  },
  {
    identityKey: "default:ekimetrics-cn",
    companyName: "Ekimetrics中国",
    industry: "数据科学 / 咨询",
    adapter: "lever",
    externalKey: "ekimetrics",
  },
  {
    identityKey: "default:coda-cn",
    companyName: "Coda Payments中国",
    industry: "游戏支付 / 金融科技",
    adapter: "lever",
    externalKey: "Coda",
  },
  {
    identityKey: "default:ppro-cn",
    companyName: "PPRO中国",
    industry: "支付 / 金融科技",
    adapter: "lever",
    externalKey: "ppro",
  },
  {
    identityKey: "default:xsolla-cn",
    companyName: "Xsolla中国",
    industry: "游戏支付 / 金融科技",
    adapter: "lever",
    externalKey: "xsolla",
  },
] as const;

const SECOND_WAVE_MOKA_SOURCES = [
  ["eyugame", "鳄游", "民营企业", "游戏", "eyugame", "47373"],
  ["bolegames", "博乐科技", "民营企业", "游戏", "bolegames", "37642"],
  ["dianhun", "电魂网络", "上市公司", "游戏", "dianhun", "55952"],
  ["shengqu", "盛趣游戏", "民营企业", "游戏", "shengqu", "4077"],
  ["yoozoo", "游族网络", "上市公司", "游戏", "yoozoo", "91950"],
  ["lovegames", "乐府互娱", "民营企业", "游戏", "lovegames", "21946"],
  ["shiyue", "诗悦网络", "民营企业", "游戏", "shiyuehr", "72054"],
  ["ey-cn", "安永中国", "外企", "专业服务", "ey", "102474"],
  ["marriott-cn", "万豪国际中国", "外企", "酒店 / 旅游", "marriott", "141002"],
  ["zeiss-cn", "蔡司中国", "外企", "光学 / 医疗科技", "zeiss", "70004"],
  ["prada-cn", "PRADA中国", "外企", "奢侈品 / 零售", "pradagroup", "151069"],
  [
    "schneider-cn",
    "施耐德电气中国",
    "外企",
    "能源管理 / 自动化",
    "se",
    "98712",
  ],
  [
    "volvo-cn",
    "沃尔沃汽车中国",
    "外企",
    "汽车 / 智能出行",
    "volvocars",
    "56034",
  ],
  ["nestle-cn", "雀巢大中华区", "外企", "食品 / 消费品", "nestlezgc", "91898"],
  ["carlsberg-cn", "嘉士伯中国", "外企", "食品饮料", "carlsberg", "37541"],
  ["garena-cn", "Garena中国", "外企", "游戏", "garena", "147001"],
  ["bigo-cn", "BIGO中国", "外企", "互联网 / 直播", "bigo", "37723"],
  ["shopee-cn", "Shopee中国", "外企", "电商", "shopee", "2962"],
  ["shein-cn", "SHEIN希音", "民营企业", "跨境电商 / 时尚", "shein", "2933"],
  ["oocl-cn", "东方海外", "外企", "航运 / 物流", "oocl", "44732"],
  [
    "tecorigin",
    "太初元碁",
    "民营企业",
    "人工智能 / 芯片",
    "tecorigin",
    "47401",
  ],
  ["3peak", "思瑞浦", "上市公司", "半导体", "3peakic", "67894"],
  [
    "highflyer",
    "幻方量化",
    "民营企业",
    "量化投资 / 人工智能",
    "high-flyer",
    "140576",
  ],
  ["stepfun", "阶跃星辰", "民营企业", "大模型 / 人工智能", "step", "94904"],
  ["baai", "北京智源研究院", "事业单位", "人工智能科研", "baai", "42174"],
  [
    "smartmore",
    "思谋科技",
    "民营企业",
    "人工智能 / 智能制造",
    "smartmore",
    "40505",
  ],
  ["meshy", "Meshy太极图形", "民营企业", "人工智能 / 3D", "taichi", "148086"],
  [
    "dolphindb",
    "DolphinDB",
    "民营企业",
    "数据库 / 金融科技",
    "dolphindb",
    "37785",
  ],
  ["jiukun", "九坤投资", "民营企业", "量化投资", "jhlfund", "46283"],
  ["lingjun", "灵均投资", "民营企业", "量化投资", "lingjuninvest", "46355"],
  ["sixie", "思勰投资", "民营企业", "量化投资", "sixiecapital", "42909"],
  ["alpha2", "Alpha2 Fund", "民营企业", "量化投资", "alpha2fund", "151123"],
  ["qianli", "千里科技", "上市公司", "智能驾驶", "qianli1", "147197"],
  ["ninebot", "九号公司", "上市公司", "智能出行 / 机器人", "ninebot", "45627"],
  ["yanfeng", "延锋", "国有企业", "汽车零部件", "yanfeng", "45086"],
  ["joyson", "均胜集团", "上市公司", "汽车零部件", "joyson", "94310"],
  ["hithium", "海辰储能", "民营企业", "储能 / 新能源", "hithium", "141287"],
  [
    "jinkosolar",
    "晶科能源",
    "上市公司",
    "光伏 / 新能源",
    "jinkosolar",
    "41896",
  ],
  ["solax", "艾罗能源", "上市公司", "光伏 / 储能", "solaxpower", "151400"],
  ["trinasolar", "天合光能", "上市公司", "光伏 / 储能", "trinasolar", "39871"],
  ["sanhua", "三花智控", "上市公司", "汽车零部件", "zjshc", "56208"],
  ["synland", "时代新安", "民营企业", "动力电池", "synland", "58041"],
  ["saj", "赛智SAJ", "民营企业", "电气 / 新能源", "saj", "54336"],
  ["smoore", "思摩尔国际", "上市公司", "消费电子", "smoore", "126055"],
  ["3songshu", "三只松鼠", "上市公司", "食品 / 消费品", "3songshu", "457"],
  ["anta", "安踏集团", "上市公司", "服饰 / 零售", "antahr", "142914"],
  ["guming", "古茗", "上市公司", "茶饮 / 消费", "guming", "39377"],
  ["wantai", "万泰生物", "上市公司", "生物医药", "ystwt", "97880"],
  ["gstzy", "固生堂", "上市公司", "医疗服务", "gstzy", "147395"],
  ["didi", "滴滴", "民营企业", "出行 / 互联网", "didiglobal", "96064"],
  ["xunlei", "迅雷", "上市公司", "互联网 / 云计算", "xunlei", "26599"],
  ["zuoyebang", "作业帮", "民营企业", "教育科技", "zuoyebang", "41328"],
  ["manbang", "满帮集团", "上市公司", "物流 / 互联网", "manbang", "46269"],
  [
    "zijin",
    "紫金矿业",
    "上市公司",
    "矿业 / 新能源材料",
    "zijinmining",
    "140688",
  ],
  ["pg-cn", "宝洁中国", "外企", "消费品", "pg", "92352"],
  ["eastmoney", "东方财富", "上市公司", "金融科技", "eastmoney", "57970"],
  ["westlake", "西湖大学", "事业单位", "科研 / 教育", "westlake", "43525"],
] as const;

const FEISHU_SOURCES = [
  ["li", "理想汽车", "汽车 / 新能源", "li.jobs.feishu.cn"],
  ["avatr", "阿维塔", "汽车 / 新能源", "xcn5vbnquq58.jobs.feishu.cn"],
  ["zeron", "零一汽车", "新能源重卡", "zeron.jobs.feishu.cn"],
  ["ecartech", "易咖智车", "无人物流车", "ecartech.jobs.feishu.cn"],
  ["ecarx", "亿咖通", "汽车电子", "ecarxgroup.jobs.feishu.cn"],
  ["desaysv", "德赛西威", "智能驾驶", "yesv-desaysv.jobs.feishu.cn"],
  ["dcar", "懂车帝", "汽车互联网", "dcar.jobs.feishu.cn"],
  ["x2robot", "自变量机器人", "具身智能", "x2-robot.jobs.feishu.cn"],
  [
    "bjhumanoid",
    "北京人形机器人创新中心",
    "人形机器人",
    "zitd5je6f7j.jobs.feishu.cn",
  ],
  ["agibot", "智元机器人", "人形机器人", "agirobot.jobs.feishu.cn"],
  ["galbot", "银河通用", "具身智能", "owm6ymi5v9b.jobs.feishu.cn", "870797"],
  ["robotera", "星动纪元", "人形机器人", "k0fqxcszc9.jobs.feishu.cn"],
  ["spirit", "千寻智能", "具身智能", "nwd4iy9rd2s.jobs.feishu.cn"],
  ["tars", "它石智航", "具身智能", "tarsrobot.jobs.feishu.cn"],
  ["flexiv", "非夕机器人", "机器人", "flexivrobotics.jobs.feishu.cn"],
  ["sharpa", "Sharpa", "灵巧手", "fcn5hvc5qbfs.jobs.feishu.cn"],
  ["mammotion", "库犸科技", "机器人", "mammotion.jobs.feishu.cn"],
  ["zhipu", "智谱AI", "大模型", "zhipu-ai.jobs.feishu.cn"],
  ["baichuan", "百川智能", "大模型", "cq6qe6bvfr6.jobs.feishu.cn"],
  ["minimax", "MiniMax", "大模型", "vrfi1sk8a0.jobs.feishu.cn"],
  ["moonshot", "月之暗面", "大模型", "moonshot.jobs.feishu.cn"],
  ["modelbest", "面壁智能", "大模型", "modelbest.jobs.feishu.cn"],
  ["01ai", "零一万物", "大模型", "01ai.jobs.feishu.cn"],
  ["infinigence", "无问芯穹", "AI Infra", "infinigence.jobs.feishu.cn"],
  ["shengshu", "生数科技", "AI视频", "shengshu.jobs.feishu.cn"],
  ["aisphere", "爱诗科技", "AI视频", "aisphere.jobs.feishu.cn"],
  ["gigaai", "极佳科技", "世界模型", "gigaai0118.jobs.feishu.cn"],
  ["aibee", "爱笔智能", "人工智能", "aibee.jobs.feishu.cn"],
  ["juzibot", "句子互动", "AI Agent", "juzihudong.jobs.feishu.cn"],
  ["shixiang", "拾象科技", "AI投研", "shixiangtech.jobs.feishu.cn"],
  ["sii", "上海创智学院", "AI科研", "sii-czxy.jobs.feishu.cn"],
  ["ponyai", "小马智行", "自动驾驶", "ponyai.jobs.feishu.cn"],
  ["holomatic", "禾多科技", "自动驾驶", "holomatic.jobs.feishu.cn"],
  ["neuehct", "智驾新程", "自动驾驶", "neuehct.jobs.feishu.cn"],
  ["mthreads", "摩尔线程", "GPU / 半导体", "mthreads.jobs.feishu.cn"],
  ["houmo", "后摩智能", "半导体", "houmo.jobs.feishu.cn"],
  ["brightchip", "光明之芯", "半导体", "brightchip.jobs.feishu.cn"],
  ["icleague", "芯盟科技", "半导体", "icleague.jobs.feishu.cn"],
  ["carizon", "酷睿程", "智能驾驶芯片", "carizon.jobs.feishu.cn"],
  ["hesai", "禾赛科技", "激光雷达", "kwh0jtf778.jobs.feishu.cn"],
  ["wanji", "万集科技", "雷达 / V2X", "fpq5u8xh3h.jobs.feishu.cn"],
  ["vast", "VAST", "AI 3D", "a9ihi0un9c.jobs.feishu.cn"],
  ["anker", "安克创新", "消费电子", "anker-in.jobs.feishu.cn"],
  ["insta360", "影石Insta360", "消费电子", "arashivision.jobs.feishu.cn"],
  ["xtool", "xTool", "智能硬件", "xtool.jobs.feishu.cn"],
  ["autel", "道通智能", "无人机", "iwpirwbutbu.jobs.feishu.cn"],
  ["thundersoft", "中科创达", "智能软件", "thundersoft.jobs.feishu.cn"],
  ["hete", "和而泰", "智能控制器", "salcje7shg.jobs.feishu.cn"],
  ["kengic", "科捷智能", "物流装备", "kengic.jobs.feishu.cn"],
  ["breo", "倍轻松", "智能穿戴", "e0cmewvq7v7.jobs.feishu.cn"],
  ["lilith", "莉莉丝", "游戏", "lilithgames.jobs.feishu.cn"],
  ["moonton", "沐瞳科技", "游戏", "moonton.jobs.feishu.cn"],
  ["coconutisland", "椰岛游戏", "游戏", "coconutisland.jobs.feishu.cn"],
  ["boomingtech", "BoomingTech", "游戏", "boomingtech.jobs.feishu.cn"],
  ["metaapp", "MetaApp", "游戏平台", "meta.jobs.feishu.cn"],
  ["xdinc", "心动网络", "游戏", "xd-legacy.jobs.feishu.cn"],
  ["wepie", "微派网络", "游戏", "wepie.jobs.feishu.cn"],
  ["hongshan", "红杉中国", "投资", "hongshan.jobs.feishu.cn"],
  ["dedao", "得到", "知识付费", "dedao.jobs.feishu.cn"],
  ["maimai", "脉脉", "互联网", "maimai.jobs.feishu.cn"],
  ["zego", "即构科技", "RTC", "zegocloud.jobs.feishu.cn"],
  ["blacklake", "黑湖科技", "工业软件", "blacklake.jobs.feishu.cn"],
  ["genki", "元气森林", "消费品", "k11pnjpvz1.jobs.feishu.cn"],
  ["ireader", "掌阅科技", "互联网", "q7w8vltyes.jobs.feishu.cn"],
  ["babycare", "Babycare", "母婴消费", "babycare.jobs.feishu.cn"],
  ["leoao", "乐刻运动", "健身", "leoao-inc.jobs.feishu.cn"],
  ["mediastorm", "影视飓风", "内容 / 传媒", "mediastorm.jobs.feishu.cn"],
  ["bluefocus", "蓝色光标", "营销", "bluefocus.jobs.feishu.cn"],
  ["cider", "Cider", "跨境电商", "ciderglobal.jobs.feishu.cn"],
  ["molbreeding", "博瑞迪", "生物育种", "molbreeding.jobs.feishu.cn"],
  ["bluepha", "蓝晶微生物", "合成生物", "bluepha.jobs.feishu.cn"],
  ["lizhi", "荔枝", "音频 / 互联网", "lizhi2021.jobs.feishu.cn"],
] as const;

/**
 * Curated public ATS boards verified on 2026-08-31. Every global ATS source is
 * constrained to mainland-China postings by countryCodes. New sources still
 * require code review because they expand the outbound allowlist.
 */
export const DEFAULT_SOURCE_CATALOG = [
  {
    identityKey: "default:xiaomi-cn",
    companyName: "小米集团",
    companyType: "民营企业",
    industry: "消费电子 / 汽车 / 人工智能",
    websiteUrl: "https://hr.xiaomi.com/",
    adapter: "xiaomi",
    externalKey: "domestic",
    baseUrl: "https://hr.xiaomi.com/website/",
    allowedHosts: ["hr.xiaomi.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  mokaSource({
    identityKey: "default:biren-cn",
    companyName: "壁仞科技",
    companyType: "民营企业",
    industry: "人工智能 / GPU / 半导体",
    orgId: "biren",
    mode: "social",
    siteId: "44726",
  }),
  mokaSource({
    identityKey: "default:talkweb-cn",
    companyName: "拓维信息",
    companyType: "上市公司",
    industry: "软件服务 / 人工智能 / 教育科技",
    orgId: "talkweb",
    mode: "social",
    siteId: "71920",
  }),
  mokaSource({
    identityKey: "default:deeproute-cn",
    companyName: "元戎启行",
    companyType: "民营企业",
    industry: "自动驾驶 / 人工智能",
    orgId: "deeproute",
    mode: "social",
    siteId: "143885",
  }),
  mokaSource({
    identityKey: "default:semitronix-cn",
    companyName: "广立微",
    companyType: "上市公司",
    industry: "半导体 / EDA / 集成电路",
    orgId: "semitronix",
    mode: "social",
    siteId: "140042",
  }),
  mokaSource({
    identityKey: "default:ztgame-cn",
    companyName: "巨人网络",
    companyType: "上市公司",
    industry: "游戏 / 数字娱乐",
    orgId: "ztgame",
    mode: "social",
    siteId: "37485",
  }),
  mokaSource({
    identityKey: "default:snb-cn",
    companyName: "苏商银行",
    companyType: "民营银行",
    industry: "金融科技 / 银行",
    orgId: "snb",
    mode: "social",
    siteId: "45591",
  }),
  mokaSource({
    identityKey: "default:bosssoft-cn",
    companyName: "博思软件",
    companyType: "上市公司",
    industry: "政务软件 / 数字财政",
    orgId: "bosssoft",
    mode: "campus",
    siteId: "68370",
  }),
  mokaSource({
    identityKey: "default:fiberhome-cn",
    companyName: "烽火通信",
    companyType: "国有企业",
    industry: "通信设备 / 光通信",
    orgId: "whfhtx",
    mode: "campus",
    siteId: "73922",
  }),
  mokaSource({
    identityKey: "default:sina-cn",
    companyName: "新浪集团",
    companyType: "民营企业",
    industry: "互联网 / 媒体 / 社交平台",
    orgId: "sina",
    mode: "campus",
    siteId: "43536",
  }),
  mokaSource({
    identityKey: "default:shokz-cn",
    companyName: "韶音科技",
    companyType: "民营企业",
    industry: "消费电子 / 声学 / 可穿戴设备",
    orgId: "aftershokzhr",
    mode: "campus",
    siteId: "36940",
  }),
  mokaSource({
    identityKey: "default:gaotu-cn",
    companyName: "高途",
    companyType: "上市公司",
    industry: "教育科技 / 互联网",
    orgId: "bjhl",
    mode: "campus",
    siteId: "102145",
  }),
  mokaSource({
    identityKey: "default:threatbook-cn",
    companyName: "微步在线",
    companyType: "民营企业",
    industry: "网络安全 / 人工智能",
    orgId: "threatbook",
    mode: "campus",
    siteId: "39679",
  }),
  mokaSource({
    identityKey: "default:huaqin-cn",
    companyName: "华勤技术",
    companyType: "上市公司",
    industry: "智能硬件 / 电子制造",
    orgId: "hq",
    mode: "campus",
    siteId: "44757",
  }),
  mokaSource({
    identityKey: "default:nsfocus-cn",
    companyName: "绿盟科技",
    companyType: "上市公司",
    industry: "网络安全 / 云安全",
    orgId: "nsfocus",
    mode: "campus",
    siteId: "29118",
  }),
  mokaSource({
    identityKey: "default:zte-cn",
    companyName: "中兴通讯",
    companyType: "上市公司",
    industry: "通信设备 / 云计算 / 芯片",
    orgId: "zte",
    mode: "campus",
    siteId: "46903",
  }),
  mokaSource({
    identityKey: "default:sph-cn",
    companyName: "上海医药",
    companyType: "国有企业",
    industry: "医药研发 / 医药流通",
    orgId: "sphchina",
    mode: "campus",
    siteId: "39826",
  }),
  mokaSource({
    identityKey: "default:weride-cn",
    companyName: "文远知行",
    companyType: "上市公司",
    industry: "自动驾驶 / 人工智能",
    orgId: "jingchi",
    mode: "campus",
    siteId: "2137",
  }),
  mokaSource({
    identityKey: "default:voyah-cn",
    companyName: "岚图汽车",
    companyType: "国有企业",
    industry: "新能源汽车 / 智能制造",
    orgId: "voyah",
    mode: "campus",
    siteId: "146293",
  }),
  mokaSource({
    identityKey: "default:deli-cn",
    companyName: "得力集团",
    companyType: "民营企业",
    industry: "文创科技 / 智能制造 / 零售",
    orgId: "nbdeli",
    mode: "campus",
    siteId: "70019",
  }),
  mokaSource({
    identityKey: "default:huahong-cn",
    companyName: "华虹集团",
    companyType: "国有企业",
    industry: "半导体 / 晶圆制造",
    orgId: "huahong",
    mode: "campus",
    siteId: "70000",
  }),
  mokaSource({
    identityKey: "default:sunny-optical-cn",
    companyName: "舜宇光学科技",
    companyType: "上市公司",
    industry: "光学 / 消费电子 / 智能制造",
    orgId: "sunnyoptical",
    mode: "campus",
    siteId: "146167",
  }),
  mokaSource({
    identityKey: "default:cambricon-cn",
    companyName: "寒武纪",
    companyType: "上市公司",
    industry: "人工智能 / AI 芯片",
    orgId: "cambricon",
    mode: "social",
  }),
  mokaSource({
    identityKey: "default:smartx-cn",
    companyName: "志凌海纳 SmartX",
    companyType: "民营企业",
    industry: "云计算 / 超融合 / 企业软件",
    orgId: "smartx",
    mode: "social",
  }),
  mokaSource({
    identityKey: "default:loctek-cn",
    companyName: "乐歌股份",
    companyType: "上市公司",
    industry: "智能家居 / 跨境电商 / 机器人",
    orgId: "loctek",
    mode: "social",
  }),
  mokaSource({
    identityKey: "default:chipjet-cn",
    companyName: "旗捷科技",
    companyType: "民营企业",
    industry: "集成电路 / 打印芯片",
    orgId: "chipjet",
    mode: "social",
  }),
  {
    identityKey: "default:bosch-cn",
    companyName: "博世中国",
    companyType: "外企",
    industry: "汽车技术 / 工业技术",
    websiteUrl: "https://jobs.smartrecruiters.com/BoschGroup",
    adapter: "smartrecruiters",
    externalKey: "BoschGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:avery-dennison-cn",
    companyName: "艾利丹尼森中国",
    companyType: "外企",
    industry: "材料科学 / 制造业",
    websiteUrl: "https://jobs.smartrecruiters.com/AveryDennison",
    adapter: "smartrecruiters",
    externalKey: "AveryDennison",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:continental-cn",
    companyName: "大陆集团中国",
    companyType: "外企",
    industry: "汽车科技 / 智能出行",
    websiteUrl: "https://jobs.smartrecruiters.com/Continental",
    adapter: "smartrecruiters",
    externalKey: "Continental",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:western-digital-cn",
    companyName: "西部数据中国",
    companyType: "外企",
    industry: "半导体 / 数据存储",
    websiteUrl: "https://jobs.smartrecruiters.com/WesternDigital",
    adapter: "smartrecruiters",
    externalKey: "WesternDigital",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:ubisoft-cn",
    companyName: "育碧中国",
    companyType: "外企",
    industry: "游戏 / 数字娱乐",
    websiteUrl: "https://jobs.smartrecruiters.com/Ubisoft2",
    adapter: "smartrecruiters",
    externalKey: "Ubisoft2",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:nielseniq-cn",
    companyName: "尼尔森IQ中国",
    companyType: "外企",
    industry: "数据分析 / 市场研究",
    websiteUrl: "https://jobs.smartrecruiters.com/NielsenIQ",
    adapter: "smartrecruiters",
    externalKey: "NielsenIQ",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:qima-cn",
    companyName: "启迈QIMA中国",
    companyType: "外企",
    industry: "质量检测 / 供应链服务",
    websiteUrl: "https://jobs.smartrecruiters.com/QIMA",
    adapter: "smartrecruiters",
    externalKey: "QIMA",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:informa-cn",
    companyName: "英富曼中国",
    companyType: "外企",
    industry: "会展 / 专业信息服务",
    websiteUrl: "https://jobs.smartrecruiters.com/InformaGroupPlc",
    adapter: "smartrecruiters",
    externalKey: "InformaGroupPlc",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:turner-townsend-cn",
    companyName: "特纳唐逊中国",
    companyType: "外企",
    industry: "工程咨询 / 项目管理",
    websiteUrl: "https://jobs.smartrecruiters.com/TurnerTownsend",
    adapter: "smartrecruiters",
    externalKey: "TurnerTownsend",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:eurofins-cn",
    companyName: "欧陆科技集团中国",
    companyType: "外企",
    industry: "检测认证 / 生命科学",
    websiteUrl: "https://jobs.smartrecruiters.com/Eurofins",
    adapter: "smartrecruiters",
    externalKey: "Eurofins",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:syngenta-cn",
    companyName: "先正达集团中国",
    companyType: "外企",
    industry: "农业科技 / 生物科学",
    websiteUrl: "https://jobs.smartrecruiters.com/SyngentaGroup",
    adapter: "smartrecruiters",
    externalKey: "SyngentaGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:renesas-cn",
    companyName: "瑞萨电子中国",
    companyType: "外企",
    industry: "半导体 / 嵌入式系统",
    websiteUrl: "https://jobs.smartrecruiters.com/RenesasElectronics",
    adapter: "smartrecruiters",
    externalKey: "RenesasElectronics",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:tomra-cn",
    companyName: "陶朗中国",
    companyType: "外企",
    industry: "智能分选 / 循环经济",
    websiteUrl: "https://jobs.smartrecruiters.com/TOMRA",
    adapter: "smartrecruiters",
    externalKey: "TOMRA",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:inter-ikea-cn",
    companyName: "宜家中国",
    companyType: "外企",
    industry: "家居零售 / 供应链",
    websiteUrl: "https://jobs.smartrecruiters.com/InterIKEAGroup",
    adapter: "smartrecruiters",
    externalKey: "InterIKEAGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:hm-cn",
    companyName: "H&M中国",
    companyType: "外企",
    industry: "时尚零售 / 电商",
    websiteUrl: "https://jobs.smartrecruiters.com/HMGroup",
    adapter: "smartrecruiters",
    externalKey: "HMGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:ldc-cn",
    companyName: "路易达孚中国",
    companyType: "外企",
    industry: "农产品 / 食品供应链",
    websiteUrl: "https://jobs.smartrecruiters.com/LouisDreyfusCompany",
    adapter: "smartrecruiters",
    externalKey: "LouisDreyfusCompany",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:third-bridge-cn",
    companyName: "Third Bridge中国",
    companyType: "外企",
    industry: "行业研究 / 专家咨询",
    websiteUrl: "https://jobs.smartrecruiters.com/ThirdBridge",
    adapter: "smartrecruiters",
    externalKey: "ThirdBridge",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  ...EXPANDED_MOKA_SOURCES.map(mokaSource),
  ...EXPANDED_PUBLIC_ATS_SOURCES.map(publicAtsSource),
  ...SECOND_WAVE_MOKA_SOURCES.map(
    ([key, companyName, companyType, industry, orgId, siteId]) =>
      mokaSource({
        identityKey: `default:${key}-cn`,
        companyName,
        companyType,
        industry,
        orgId,
        mode: "social",
        siteId,
      }),
  ),
  ...FEISHU_SOURCES.map(([key, companyName, industry, host, path]) =>
    feishuSource({
      identityKey: `default:${key}-cn`,
      companyName,
      industry,
      host,
      path,
    }),
  ),
] as const satisfies readonly DefaultSourceCatalogEntry[];

export function publicDefaultSourceCatalog() {
  return DEFAULT_SOURCE_CATALOG.map(
    ({ companyName, adapter, industry, websiteUrl }) => ({
      companyName,
      adapter,
      industry,
      websiteUrl,
    }),
  );
}
