import type { SourceAdapterKind } from "../domain/entities";

export type DefaultSourceCatalogEntry = {
  identityKey: string;
  companyName: string;
  companyType: string;
  industry: string;
  websiteUrl: string;
  adapter: SourceAdapterKind;
  externalKey: string;
  baseUrl: string;
  allowedHosts: string[];
  countryCodes: string[];
  syncIntervalMinutes: number;
};

function mokaSource(input: {
  identityKey: string;
  companyName: string;
  companyType: string;
  industry: string;
  orgId: string;
  mode: "social" | "campus";
  siteId?: string;
}) {
  const portal =
    input.mode === "campus" ? "campus-recruitment" : "social-recruitment";
  const sitePath = input.siteId ? `/${input.siteId}` : "";
  return {
    identityKey: input.identityKey,
    companyName: input.companyName,
    companyType: input.companyType,
    industry: input.industry,
    websiteUrl: `https://app.mokahr.com/${portal}/${input.orgId}${sitePath}`,
    adapter: "moka" as const,
    externalKey: `${input.orgId}|${input.mode}|${input.siteId ?? ""}`,
    baseUrl: "https://api.mokahr.com/",
    allowedHosts: ["api.mokahr.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  };
}

/**
 * Curated public ATS boards verified on 2026-08-31. Every global ATS source is
 * constrained to mainland-China postings by countryCodes. New sources still
 * require code review because they expand the outbound allowlist.
 */
export const DEFAULT_SOURCE_CATALOG = [
  {
    identityKey: "default:xiaomi-cn",
    companyName: "小米集团",
    companyType: "民营企业",
    industry: "消费电子 / 汽车 / 人工智能",
    websiteUrl: "https://hr.xiaomi.com/",
    adapter: "xiaomi",
    externalKey: "domestic",
    baseUrl: "https://hr.xiaomi.com/website/",
    allowedHosts: ["hr.xiaomi.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  mokaSource({
    identityKey: "default:biren-cn",
    companyName: "壁仞科技",
    companyType: "民营企业",
    industry: "人工智能 / GPU / 半导体",
    orgId: "biren",
    mode: "social",
    siteId: "44726",
  }),
  mokaSource({
    identityKey: "default:talkweb-cn",
    companyName: "拓维信息",
    companyType: "上市公司",
    industry: "软件服务 / 人工智能 / 教育科技",
    orgId: "talkweb",
    mode: "social",
    siteId: "71920",
  }),
  mokaSource({
    identityKey: "default:deeproute-cn",
    companyName: "元戎启行",
    companyType: "民营企业",
    industry: "自动驾驶 / 人工智能",
    orgId: "deeproute",
    mode: "social",
    siteId: "143885",
  }),
  mokaSource({
    identityKey: "default:semitronix-cn",
    companyName: "广立微",
    companyType: "上市公司",
    industry: "半导体 / EDA / 集成电路",
    orgId: "semitronix",
    mode: "social",
    siteId: "140042",
  }),
  mokaSource({
    identityKey: "default:ztgame-cn",
    companyName: "巨人网络",
    companyType: "上市公司",
    industry: "游戏 / 数字娱乐",
    orgId: "ztgame",
    mode: "social",
    siteId: "37485",
  }),
  mokaSource({
    identityKey: "default:snb-cn",
    companyName: "苏商银行",
    companyType: "民营银行",
    industry: "金融科技 / 银行",
    orgId: "snb",
    mode: "social",
    siteId: "45591",
  }),
  mokaSource({
    identityKey: "default:bosssoft-cn",
    companyName: "博思软件",
    companyType: "上市公司",
    industry: "政务软件 / 数字财政",
    orgId: "bosssoft",
    mode: "campus",
    siteId: "68370",
  }),
  mokaSource({
    identityKey: "default:fiberhome-cn",
    companyName: "烽火通信",
    companyType: "国有企业",
    industry: "通信设备 / 光通信",
    orgId: "whfhtx",
    mode: "campus",
    siteId: "73922",
  }),
  mokaSource({
    identityKey: "default:sina-cn",
    companyName: "新浪集团",
    companyType: "民营企业",
    industry: "互联网 / 媒体 / 社交平台",
    orgId: "sina",
    mode: "campus",
    siteId: "43536",
  }),
  mokaSource({
    identityKey: "default:shokz-cn",
    companyName: "韶音科技",
    companyType: "民营企业",
    industry: "消费电子 / 声学 / 可穿戴设备",
    orgId: "aftershokzhr",
    mode: "campus",
    siteId: "36940",
  }),
  mokaSource({
    identityKey: "default:gaotu-cn",
    companyName: "高途",
    companyType: "上市公司",
    industry: "教育科技 / 互联网",
    orgId: "bjhl",
    mode: "campus",
    siteId: "102145",
  }),
  mokaSource({
    identityKey: "default:threatbook-cn",
    companyName: "微步在线",
    companyType: "民营企业",
    industry: "网络安全 / 人工智能",
    orgId: "threatbook",
    mode: "campus",
    siteId: "39679",
  }),
  mokaSource({
    identityKey: "default:huaqin-cn",
    companyName: "华勤技术",
    companyType: "上市公司",
    industry: "智能硬件 / 电子制造",
    orgId: "hq",
    mode: "campus",
    siteId: "44757",
  }),
  mokaSource({
    identityKey: "default:nsfocus-cn",
    companyName: "绿盟科技",
    companyType: "上市公司",
    industry: "网络安全 / 云安全",
    orgId: "nsfocus",
    mode: "campus",
    siteId: "29118",
  }),
  mokaSource({
    identityKey: "default:zte-cn",
    companyName: "中兴通讯",
    companyType: "上市公司",
    industry: "通信设备 / 云计算 / 芯片",
    orgId: "zte",
    mode: "campus",
    siteId: "46903",
  }),
  mokaSource({
    identityKey: "default:sph-cn",
    companyName: "上海医药",
    companyType: "国有企业",
    industry: "医药研发 / 医药流通",
    orgId: "sphchina",
    mode: "campus",
    siteId: "39826",
  }),
  mokaSource({
    identityKey: "default:weride-cn",
    companyName: "文远知行",
    companyType: "上市公司",
    industry: "自动驾驶 / 人工智能",
    orgId: "jingchi",
    mode: "campus",
    siteId: "2137",
  }),
  mokaSource({
    identityKey: "default:voyah-cn",
    companyName: "岚图汽车",
    companyType: "国有企业",
    industry: "新能源汽车 / 智能制造",
    orgId: "voyah",
    mode: "campus",
    siteId: "146293",
  }),
  mokaSource({
    identityKey: "default:deli-cn",
    companyName: "得力集团",
    companyType: "民营企业",
    industry: "文创科技 / 智能制造 / 零售",
    orgId: "nbdeli",
    mode: "campus",
    siteId: "70019",
  }),
  mokaSource({
    identityKey: "default:huahong-cn",
    companyName: "华虹集团",
    companyType: "国有企业",
    industry: "半导体 / 晶圆制造",
    orgId: "huahong",
    mode: "campus",
    siteId: "70000",
  }),
  mokaSource({
    identityKey: "default:sunny-optical-cn",
    companyName: "舜宇光学科技",
    companyType: "上市公司",
    industry: "光学 / 消费电子 / 智能制造",
    orgId: "sunnyoptical",
    mode: "campus",
    siteId: "146167",
  }),
  mokaSource({
    identityKey: "default:cambricon-cn",
    companyName: "寒武纪",
    companyType: "上市公司",
    industry: "人工智能 / AI 芯片",
    orgId: "cambricon",
    mode: "social",
  }),
  mokaSource({
    identityKey: "default:smartx-cn",
    companyName: "志凌海纳 SmartX",
    companyType: "民营企业",
    industry: "云计算 / 超融合 / 企业软件",
    orgId: "smartx",
    mode: "social",
  }),
  mokaSource({
    identityKey: "default:loctek-cn",
    companyName: "乐歌股份",
    companyType: "上市公司",
    industry: "智能家居 / 跨境电商 / 机器人",
    orgId: "loctek",
    mode: "social",
  }),
  mokaSource({
    identityKey: "default:chipjet-cn",
    companyName: "旗捷科技",
    companyType: "民营企业",
    industry: "集成电路 / 打印芯片",
    orgId: "chipjet",
    mode: "social",
  }),
  {
    identityKey: "default:bosch-cn",
    companyName: "博世中国",
    companyType: "外企",
    industry: "汽车技术 / 工业技术",
    websiteUrl: "https://www.bosch.com.cn/",
    adapter: "smartrecruiters",
    externalKey: "BoschGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:avery-dennison-cn",
    companyName: "艾利丹尼森中国",
    companyType: "外企",
    industry: "材料科学 / 制造业",
    websiteUrl: "https://www.averydennison.cn/",
    adapter: "smartrecruiters",
    externalKey: "AveryDennison",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:continental-cn",
    companyName: "大陆集团中国",
    companyType: "外企",
    industry: "汽车科技 / 智能出行",
    websiteUrl: "https://www.continental.com/zh-cn/",
    adapter: "smartrecruiters",
    externalKey: "Continental",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:western-digital-cn",
    companyName: "西部数据中国",
    companyType: "外企",
    industry: "半导体 / 数据存储",
    websiteUrl: "https://www.westerndigital.com/zh-cn/",
    adapter: "smartrecruiters",
    externalKey: "WesternDigital",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:ubisoft-cn",
    companyName: "育碧中国",
    companyType: "外企",
    industry: "游戏 / 数字娱乐",
    websiteUrl: "https://www.ubisoft.com/zh-cn/company/careers",
    adapter: "smartrecruiters",
    externalKey: "Ubisoft2",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:nielseniq-cn",
    companyName: "尼尔森IQ中国",
    companyType: "外企",
    industry: "数据分析 / 市场研究",
    websiteUrl: "https://nielseniq.com/global/zh/",
    adapter: "smartrecruiters",
    externalKey: "NielsenIQ",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:qima-cn",
    companyName: "启迈QIMA中国",
    companyType: "外企",
    industry: "质量检测 / 供应链服务",
    websiteUrl: "https://www.qima.com/zh-cn/",
    adapter: "smartrecruiters",
    externalKey: "QIMA",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:informa-cn",
    companyName: "英富曼中国",
    companyType: "外企",
    industry: "会展 / 专业信息服务",
    websiteUrl: "https://www.informa.com/",
    adapter: "smartrecruiters",
    externalKey: "InformaGroupPlc",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:turner-townsend-cn",
    companyName: "特纳唐逊中国",
    companyType: "外企",
    industry: "工程咨询 / 项目管理",
    websiteUrl: "https://www.turnerandtownsend.com/",
    adapter: "smartrecruiters",
    externalKey: "TurnerTownsend",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:eurofins-cn",
    companyName: "欧陆科技集团中国",
    companyType: "外企",
    industry: "检测认证 / 生命科学",
    websiteUrl: "https://www.eurofins.cn/",
    adapter: "smartrecruiters",
    externalKey: "Eurofins",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:syngenta-cn",
    companyName: "先正达集团中国",
    companyType: "外企",
    industry: "农业科技 / 生物科学",
    websiteUrl: "https://www.syngentagroup.cn/",
    adapter: "smartrecruiters",
    externalKey: "SyngentaGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:renesas-cn",
    companyName: "瑞萨电子中国",
    companyType: "外企",
    industry: "半导体 / 嵌入式系统",
    websiteUrl: "https://www.renesas.cn/",
    adapter: "smartrecruiters",
    externalKey: "RenesasElectronics",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:tomra-cn",
    companyName: "陶朗中国",
    companyType: "外企",
    industry: "智能分选 / 循环经济",
    websiteUrl: "https://www.tomra.com/zh-cn",
    adapter: "smartrecruiters",
    externalKey: "TOMRA",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:inter-ikea-cn",
    companyName: "宜家中国",
    companyType: "外企",
    industry: "家居零售 / 供应链",
    websiteUrl: "https://www.inter.ikea.com/",
    adapter: "smartrecruiters",
    externalKey: "InterIKEAGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:hm-cn",
    companyName: "H&M中国",
    companyType: "外企",
    industry: "时尚零售 / 电商",
    websiteUrl: "https://career.hm.com/",
    adapter: "smartrecruiters",
    externalKey: "HMGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:ldc-cn",
    companyName: "路易达孚中国",
    companyType: "外企",
    industry: "农产品 / 食品供应链",
    websiteUrl: "https://www.ldc.com/cn/zh/",
    adapter: "smartrecruiters",
    externalKey: "LouisDreyfusCompany",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:third-bridge-cn",
    companyName: "Third Bridge中国",
    companyType: "外企",
    industry: "行业研究 / 专家咨询",
    websiteUrl: "https://www.thirdbridge.com/",
    adapter: "smartrecruiters",
    externalKey: "ThirdBridge",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
] as const satisfies readonly DefaultSourceCatalogEntry[];

export function publicDefaultSourceCatalog() {
  return DEFAULT_SOURCE_CATALOG.map(
    ({ companyName, adapter, industry, websiteUrl }) => ({
      companyName,
      adapter,
      industry,
      websiteUrl,
    }),
  );
}
