import type { SourceAdapterKind } from "../domain/entities";

export type DefaultSourceCatalogEntry = {
  identityKey: string;
  companyName: string;
  companyType: string;
  industry: string;
  websiteUrl: string;
  adapter: SourceAdapterKind;
  externalKey: string;
  baseUrl: string;
  allowedHosts: string[];
  countryCodes: string[];
  syncIntervalMinutes: number;
};

/**
 * Curated public ATS boards verified on 2026-08-31. Every global ATS source is
 * constrained to mainland-China postings by countryCodes. New sources still
 * require code review because they expand the outbound allowlist.
 */
export const DEFAULT_SOURCE_CATALOG = [
  {
    identityKey: "default:xiaomi-cn",
    companyName: "小米集团",
    companyType: "民营企业",
    industry: "消费电子 / 汽车 / 人工智能",
    websiteUrl: "https://hr.xiaomi.com/",
    adapter: "xiaomi",
    externalKey: "domestic",
    baseUrl: "https://hr.xiaomi.com/website/",
    allowedHosts: ["hr.xiaomi.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:bosch-cn",
    companyName: "博世中国",
    companyType: "外企",
    industry: "汽车技术 / 工业技术",
    websiteUrl: "https://www.bosch.com.cn/",
    adapter: "smartrecruiters",
    externalKey: "BoschGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:avery-dennison-cn",
    companyName: "艾利丹尼森中国",
    companyType: "外企",
    industry: "材料科学 / 制造业",
    websiteUrl: "https://www.averydennison.cn/",
    adapter: "smartrecruiters",
    externalKey: "AveryDennison",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:continental-cn",
    companyName: "大陆集团中国",
    companyType: "外企",
    industry: "汽车科技 / 智能出行",
    websiteUrl: "https://www.continental.com/zh-cn/",
    adapter: "smartrecruiters",
    externalKey: "Continental",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:western-digital-cn",
    companyName: "西部数据中国",
    companyType: "外企",
    industry: "半导体 / 数据存储",
    websiteUrl: "https://www.westerndigital.com/zh-cn/",
    adapter: "smartrecruiters",
    externalKey: "WesternDigital",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:ubisoft-cn",
    companyName: "育碧中国",
    companyType: "外企",
    industry: "游戏 / 数字娱乐",
    websiteUrl: "https://www.ubisoft.com/zh-cn/company/careers",
    adapter: "smartrecruiters",
    externalKey: "Ubisoft2",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:nielseniq-cn",
    companyName: "尼尔森IQ中国",
    companyType: "外企",
    industry: "数据分析 / 市场研究",
    websiteUrl: "https://nielseniq.com/global/zh/",
    adapter: "smartrecruiters",
    externalKey: "NielsenIQ",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:qima-cn",
    companyName: "启迈QIMA中国",
    companyType: "外企",
    industry: "质量检测 / 供应链服务",
    websiteUrl: "https://www.qima.com/zh-cn/",
    adapter: "smartrecruiters",
    externalKey: "QIMA",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:informa-cn",
    companyName: "英富曼中国",
    companyType: "外企",
    industry: "会展 / 专业信息服务",
    websiteUrl: "https://www.informa.com/",
    adapter: "smartrecruiters",
    externalKey: "InformaGroupPlc",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:turner-townsend-cn",
    companyName: "特纳唐逊中国",
    companyType: "外企",
    industry: "工程咨询 / 项目管理",
    websiteUrl: "https://www.turnerandtownsend.com/",
    adapter: "smartrecruiters",
    externalKey: "TurnerTownsend",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:eurofins-cn",
    companyName: "欧陆科技集团中国",
    companyType: "外企",
    industry: "检测认证 / 生命科学",
    websiteUrl: "https://www.eurofins.cn/",
    adapter: "smartrecruiters",
    externalKey: "Eurofins",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:syngenta-cn",
    companyName: "先正达集团中国",
    companyType: "外企",
    industry: "农业科技 / 生物科学",
    websiteUrl: "https://www.syngentagroup.cn/",
    adapter: "smartrecruiters",
    externalKey: "SyngentaGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:renesas-cn",
    companyName: "瑞萨电子中国",
    companyType: "外企",
    industry: "半导体 / 嵌入式系统",
    websiteUrl: "https://www.renesas.cn/",
    adapter: "smartrecruiters",
    externalKey: "RenesasElectronics",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:tomra-cn",
    companyName: "陶朗中国",
    companyType: "外企",
    industry: "智能分选 / 循环经济",
    websiteUrl: "https://www.tomra.com/zh-cn",
    adapter: "smartrecruiters",
    externalKey: "TOMRA",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:inter-ikea-cn",
    companyName: "宜家中国",
    companyType: "外企",
    industry: "家居零售 / 供应链",
    websiteUrl: "https://www.inter.ikea.com/",
    adapter: "smartrecruiters",
    externalKey: "InterIKEAGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:hm-cn",
    companyName: "H&M中国",
    companyType: "外企",
    industry: "时尚零售 / 电商",
    websiteUrl: "https://career.hm.com/",
    adapter: "smartrecruiters",
    externalKey: "HMGroup",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:ldc-cn",
    companyName: "路易达孚中国",
    companyType: "外企",
    industry: "农产品 / 食品供应链",
    websiteUrl: "https://www.ldc.com/cn/zh/",
    adapter: "smartrecruiters",
    externalKey: "LouisDreyfusCompany",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
  {
    identityKey: "default:third-bridge-cn",
    companyName: "Third Bridge中国",
    companyType: "外企",
    industry: "行业研究 / 专家咨询",
    websiteUrl: "https://www.thirdbridge.com/",
    adapter: "smartrecruiters",
    externalKey: "ThirdBridge",
    baseUrl: "https://api.smartrecruiters.com/",
    allowedHosts: ["api.smartrecruiters.com"],
    countryCodes: ["cn"],
    syncIntervalMinutes: 360,
  },
] as const satisfies readonly DefaultSourceCatalogEntry[];

export function publicDefaultSourceCatalog() {
  return DEFAULT_SOURCE_CATALOG.map(
    ({ companyName, adapter, industry, websiteUrl }) => ({
      companyName,
      adapter,
      industry,
      websiteUrl,
    }),
  );
}
