from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import psycopg
from env import load_local_env


TABLES = (
    "accounts", "admin_audit_events", "applications", "application_events",
    "application_stage_occurrences", "import_batches", "import_rows", "sessions",
    "users", "verification_tokens",
)


def render(schema: dict[str, list[dict[str, object]]]) -> str:
    content = "// Generated by scripts/db_types.py. Do not edit.\n"
    content += "export const databaseSchema = " + json.dumps(schema, ensure_ascii=False, indent=2) + " as const;\n"
    content += "export type DatabaseSchema = typeof databaseSchema;\n"
    return content


def read_schema(cursor: psycopg.Cursor) -> dict[str, list[dict[str, object]]]:
    cursor.execute(
        """
        select table_name, column_name, data_type, is_nullable
        from information_schema.columns
        where table_schema='public' and table_name = any(%s)
        order by table_name, ordinal_position
        """,
        (list(TABLES),),
    )
    schema: dict[str, list[dict[str, object]]] = {}
    for table, column, data_type, nullable in cursor.fetchall():
        schema.setdefault(table, []).append(
            {"name": column, "type": data_type, "nullable": nullable == "YES"}
        )
    return schema


def write_types(schema: dict[str, list[dict[str, object]]]) -> None:
    Path("src/generated/database.types.ts").write_text(render(schema), encoding="utf-8")


def main() -> None:
    load_local_env()
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise SystemExit("DATABASE_URL is required")
    with psycopg.connect(url) as connection, connection.cursor() as cursor:
        schema = read_schema(cursor)
    target = Path("src/generated/database.types.ts")
    content = render(schema)
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            raise SystemExit("database types drift detected; run pnpm db:types")
        print("PASS generated database types are current")
    else:
        write_types(schema)


if __name__ == "__main__": main()
