from __future__ import annotations

import json
import os
from pathlib import Path

import psycopg


def main() -> None:
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise SystemExit("DATABASE_URL is required")
    with psycopg.connect(url) as connection, connection.cursor() as cursor:
        cursor.execute(
            """
            select table_name, column_name, data_type, is_nullable
            from information_schema.columns
            where table_schema='public'
              and table_name in ('applications','application_stage_occurrences','application_events','import_batches','import_rows')
            order by table_name, ordinal_position
            """
        )
        schema: dict[str, list[dict[str, object]]] = {}
        for table, column, data_type, nullable in cursor.fetchall():
            schema.setdefault(table, []).append(
                {"name": column, "type": data_type, "nullable": nullable == "YES"}
            )
    content = "// Generated by scripts/db_types.py. Do not edit.\n"
    content += "export const databaseSchema = " + json.dumps(schema, ensure_ascii=False, indent=2) + " as const;\n"
    content += "export type DatabaseSchema = typeof databaseSchema;\n"
    Path("src/generated/database.types.ts").write_text(content, encoding="utf-8")


if __name__ == "__main__": main()
